apiVersion: v1
kind: Service
metadata:
  name: arcade-api
  labels:
    app: arcade-api
spec:
  selector:
    app: arcade-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
  # Pour accéder depuis l'extérieur :
  #   kubectl port-forward svc/arcade-api 8000:80
  # Ou changer type: ClusterIP -> NodePort pour un accès direct
